# Generated by Django 4.2.11 on 2024-03-23 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Noticias",
            fields=[
                (
                    "cod_noticia",
                    models.IntegerField(
                        max_length=20, primary_key=True, serialize=False
                    ),
                ),
                ("texto", models.TextField()),
                ("titulo", models.CharField(max_length=100)),
                ("autor", models.CharField(max_length=50)),
                ("categoria", models.CharField(max_length=50)),
                ("data", models.DateField(help_text="aaaa/mm/dd")),
                ("create_timestamp", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
