# Generated by Django 4.2.11 on 2024-03-23 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("noticias", "0002_alter_noticias_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="noticias",
            name="create_timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
