# Generated by Django 4.2.11 on 2024-03-24 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("noticias", "0003_alter_noticias_create_timestamp"),
    ]

    operations = [
        migrations.CreateModel(
            name="Imagens",
            fields=[
                (
                    "cod_imagem",
                    models.IntegerField(
                        max_length=20, primary_key=True, serialize=False
                    ),
                ),
                ("path", models.ImageField(upload_to="noticiaImg")),
                ("extencao", models.CharField(max_length=4)),
                ("create_timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "cod_noticia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="noticias.noticias",
                    ),
                ),
            ],
        ),
    ]
